name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  PROJECT_REGION: ${{ vars.GCP_PROJECT_REGION }}
  SERVICE_NAME: ${{ vars.GCP_SERVICE_API_NAME }}
  ARTIFACT_REGISTRY: ${{ vars.GCP_ARTIFACT_REGISTRY }}

jobs:
  build-and-push:
    name: Build and Push to Artifact Registry
    runs-on: ubuntu-latest
    environment: GCP-Rozen
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ vars.GCP_SA_EMAIL }}'
          create_credentials_file: true
          export_environment_variables: true
          universe: 'googleapis.com'
          cleanup_credentials: true
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'
          id_token_include_email: false

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.PROJECT_REGION }}-docker.pkg.dev

      - name: Define image tag
        id: image_tag
        run: echo "TAG=${{ env.PROJECT_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |-
          docker build -t $TAG .
          docker push $TAG

  deploy-to-cloud-run:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: GCP-Rozen
    #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    if: github.event_name == 'push'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ vars.GCP_SA_EMAIL }}'
          create_credentials_file: true
          export_environment_variables: true
          universe: 'googleapis.com'
          cleanup_credentials: true
          access_token_lifetime: '3600s'
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'
          id_token_include_email: false

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Define image tag for deployment
        id: image_tag
        run: echo "TAG=${{ env.PROJECT_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $TAG \
            --region ${{ env.PROJECT_REGION }} \
            --service-account ${{ vars.GCP_SA_EMAIL }} \
            --max-instances=${{ vars.GCP_SERVICE_API_MAX_INSTANCES }} \
            --set-secrets=TELEGRAM_BOT_TOKEN=${{ vars.GCP_DCUBABOT_SECRET_TG_BOT_TOKEN }}:latest \
            --set-secrets=DB_URL=${{ vars.GCP_SECRET_DB_URL }}:latest \
            --set-secrets=DB_USER=${{ vars.GCP_SECRET_DB_USER }}:latest \
            --set-secrets=DB_PASSWORD=${{ vars.GCP_SECRET_DB_PASSWORD }}:latest \
            --set-env-vars=DB_PORT=${{ vars.GCP_DB_PORT }} \
            --set-secrets=S3_ACCESS_ID=${{ vars.GCP_SECRET_S3_ACCESS_ID }}:latest \
            --set-secrets=S3_ACCESS_SECRET=${{ vars.GCP_SECRET_S3_ACCESS_SECRET }}:latest \
            --set-secrets=S3_HOST=${{ vars.GCP_SECRET_S3_HOST }}:latest \
            --set-env-vars=S3_BUCKET=${{ vars.GCP_S3_BUCKET }} \
            --platform managed \
            --allow-unauthenticated
